version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    networks:
      net-dfindexer:
        ipv4_address: 172.50.0.100
    volumes:
      - ./redis_data:/data

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped
    networks:
      net-dfindexer:
        ipv4_address: 172.50.0.101
    environment:
      - LOG_LEVEL=info
      - TZ=America/Sao_Paulo

  indexer:
    image: ghcr.io/dflexy/dfindexer:latest
    container_name: dfindexer
    restart: unless-stopped
    networks:
      net-dfindexer:
        ipv4_address: 172.50.0.102
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FLARESOLVERR_ADDRESS=http://flaresolverr:8191
      - PORT=7006
      - LOG_LEVEL=1
      - LOG_FORMAT=console
      - TRACKER_SCRAPING_ENABLED=true
    depends_on:
      - redis
      - flaresolverr

  prowlarr:
    image: ghcr.io/hotio/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    networks:
      net-dfindexer:
        ipv4_address: 172.50.0.103
    environment:
      - TZ=America_Sao_Paulo
    ports:
      - "9696:9696"
    volumes:
      - ./prowlarr:/config

# ========================
# Rede customizada
# ========================
networks:
  net-dfindexer:
    driver: bridge
    ipam:
      config:
        - subnet: 172.50.0.0/24
          gateway: 172.50.0.1
